"""Integrations — Bermi AI beyond chat.

Phase 1 ships the integration framework and status reporting. Google
Calendar activates once GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET are
configured (a Google Cloud OAuth consent screen and credentials are
required — they cannot be generated by the application itself).
"""

from fastapi import APIRouter, Depends

from ..auth import get_current_user
from ..config import get_settings
from ..models import User

router = APIRouter(prefix="/api/integrations", tags=["integrations"])


@router.get("")
def list_integrations(user: User = Depends(get_current_user)):
    settings = get_settings()
    google_configured = bool(settings.google_client_id and settings.google_client_secret)
    return [
        {
            "id": "google_calendar",
            "name": "Google Calendar",
            "description": "Let Bermi AI read your schedule and create events "
            "from conversations (e.g. deadlines from a proposal).",
            "available": google_configured,
            "connected": False,
            "note": None
            if google_configured
            else "Awaiting Google Cloud OAuth credentials (GOOGLE_CLIENT_ID / "
            "GOOGLE_CLIENT_SECRET) — coming online soon.",
        },
    ]
